development:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: rstation_development
  pool:     5
  username: rstation
  password:
  template: template0

test:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: rstation_test
  pool:     5
  username: rstation
  password:
  template: template0

production:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: rstation_production
  pool:     5
  username: rstation
  password:
  template: template0
