# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4a7a5d5157d7f09d10d667d338a649087e09442580a64447d9e400f1978ae74a7bae334a392f84380cf23b305201f21234bd5b6eb3eab7e759a9a327c4251ab0

test:
  secret_key_base: 17fcffc0ddae08d9e23ac75f9a68a13c8e258b78068a13f0aef9b7f38004d8213c8a2809caab7cd0ac4ae19562ceb78331cd21c39ad27fa60038fe719537d460

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
